#!/usr/bin/env ruby

base_dir = File.expand_path("../..", __FILE__)
lib_dir = File.join(base_dir, "lib")
$LOAD_PATH.unshift(lib_dir)

require "aligntext"

require "optparse"
options = {}
option_parser = OptionParser.new
option_parser.on("-s", "--separator SEPARATOR") do |separator|
  options[:separator] = separator
end
option_parser.on("-v", "--version") do |separator|
  puts Aligntext::VERSION
  exit
end
option_parser.parse!(ARGV)

formatter = Aligntext::Formatter.new(options)
puts formatter.align(ARGF.read)
