#!/usr/bin/env ruby

#require "aligntext"

require "optparse"
options = {}
option_parser = OptionParser.new
option_parser.on("-s", "--separator [String]") do |separator|
  options[:separator] = separator
end
option_parser.parse!(ARGV)

separator = options[:separator] || " "
max_index = 0

source_lines = ARGF.to_a

source_lines.each do |line|
  index = line.index(separator)
  next unless index
  if index > max_index
    max_index = index
  end
end

source_lines.each do |line|
  index = line.index(separator)
  unless index
    puts line
    next
  end
  if index < max_index
    puts line.insert(index, " " * (max_index - index))
  else
    puts line
  end
end
